name: Build

on:
  # this opts us in to be a reusable workflow.
  # https://docs.github.com/en/actions/sharing-automations/reusing-workflows#creating-a-reusable-workflow
  workflow_call:
    secrets:
      DOCKER_CREDS:
        description: 'Container registry credentials to push (non-GHCR) images with (optional)'
        required: false

jobs:
  build:
    # we mainly just need to be able to run Docker
    runs-on: ubuntu-latest
    steps:
    # checks out the content of the repository. it's a bit weird to explicitly ask for it 🤷
    - uses: actions/checkout@v6

    # wires up binfmt_misc (https://docs.kernel.org/admin-guide/binfmt-misc.html) to transparently handle foreign
    # architecture executables in userspace. this enables us to do Docker builds for architectures other than the host.
    - uses: docker/setup-qemu-action@v4
      with:
        platforms: riscv64,arm64,arm

    # does the equivalent of `docker/setup-buildx-action` but it's a small thing to implement ourselves without adding another dependency
    - name: Configure builder
      run: |
        set -eu
        # configures `docker-container` as driver for buildx (to support multi-architecture builds which the default `docker` would not).
        # https://docs.docker.com/reference/cli/docker/buildx/create/#driver
        docker buildx create --driver=docker-container --name=turbobob --use --bootstrap

    # does the equivalent of `$ bob build`
    - name: Build
      run: |
        set -eu
        # If DOCKER_CREDS is unset or empty, use creds for GitHub's GHCR
        if [ -z "${DOCKER_CREDS-}" ]; then
          export DOCKER_CREDS="${DOCKER_CREDS_FOR_GITHUB-}"
        fi
        
        # better to not store in local workdir (would always make workdir unclean Git-wise)
        docker run --rm -v /usr/local/bin:/host --entrypoint= ghcr.io/function61/turbobob:latest sh -c 'cp $(which bob) /host/'
        bob build in-ci-autodetect-settings
      env:
        DOCKER_CREDS: ${{ secrets.DOCKER_CREDS }}
        DOCKER_CREDS_FOR_GITHUB: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
